VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Ssl"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Function LvsJnComma$(Lvs$)
'Stop
''LvsJnComma = JnComma(SslSy(Lvs))
'End Function
'
'Function LvsJnQuoteComma$(Lvs$)
'Stop
''LvsJnQuoteComma = JnComma(AyQuote(SslSy(Lvs), "'"))
'End Function
'
