VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "MthBrkOpt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public AllLines As Boolean, BrkNm As Boolean, BrkAll As Boolean, TopRmk As Boolean
Public NmIdCnt As Boolean, LinesIdCnt As Boolean, MdTy As Boolean, MthPfx As Boolean

Property Get Fldss$()
Fldss = ""
End Property

