VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "DCRslt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Public Nm1$, Nm2$
Public AExcess As New Dictionary
Public BExcess As New Dictionary
Public ADif As New Dictionary
Public BDif As New Dictionary
Public Sam As New Dictionary
