VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Tst"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Sub M_Ay()
QVb.M_Ay.ZZ__Tst
End Sub

Sub M_Brk()
QVb.M_Brk.ZZ__Tst
End Sub

Sub M_Dic()
QVb.M_Dic.ZZ__Tst
End Sub

Sub M_Is()
QVb.M_Is.ZZ__Tst
End Sub

Sub M_Lin()
QVb.M_Lin.ZZ__Tst
End Sub

Sub M_Lines()
QVb.M_Lines.ZZ__Tst
End Sub

Sub M_Pth()
QVb.M_Pth.ZZ__Tst
End Sub

Sub M_Rmv()
QVb.M_Rmv.ZZ__Tst
End Sub

Sub M_Rpl()
QVb.M_Rpl.ZZ__Tst
End Sub

Sub M_S1S2Ay()
QVb.M_S1S2Ay.ZZ__Tst
End Sub

Sub M_Tak()
QVb.M_Tak.ZZ__Tst
End Sub

Sub M_Vbl()
QVb.M_Vbl.ZZ__Tst
End Sub

Sub M_VblAy()
QVb.M_VblAy.ZZ__Tst
End Sub

Sub SyPair()
Dim A As New SyPair: A.ZZ__Tst
End Sub
