VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Tst"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Sub M_Ay()
QVb.M_Ay.ZZZ__Tst
End Sub

Sub M_Brk()
QVb.M_Brk.ZZZ__Tst
End Sub

Sub M_Dic()
QVb.M_Dic.ZZZ__Tst
End Sub

Sub M_Is()
QVb.M_Is.ZZZ__Tst
End Sub

Sub M_Lin()
QVb.M_Lin.ZZZ__Tst
End Sub

Sub M_Lines()
QVb.M_Lines.ZZZ__Tst
End Sub

Sub M_Pth()
QVb.M_Pth.ZZZ__Tst
End Sub

Sub M_Rmv()
QVb.M_Rmv.ZZZ__Tst
End Sub

Sub M_Rpl()
QVb.M_Rpl.ZZZ__Tst
End Sub

Sub M_Tak()
QVb.M_Tak.ZZZ__Tst
End Sub

Sub M_Vbl()
QVb.M_Vbl.ZZZ__Tst
End Sub

Sub M_VblAy()
QVb.M_VblAy.ZZZ__Tst
End Sub

Sub SyPair()
Dim A As New SyPair: A.ZZZ__Tst
End Sub
