VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Emp"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Function Ay() As Variant()
End Function

Function BoolAy() As Boolean()
End Function

Function BytAy() As Byte()
End Function

Function DblAy() As Double()
End Function

Function DteAy() As Date()
End Function

Function FmTo() As FmTo
FmTo.FmIx = -1
FmTo.ToIx = -1
End Function

Function IntAy() As Integer()
End Function

Function LngAy() As Long()
End Function

Function RRCC() As RRCC
End Function

Function SngAy() As Single()
End Function

Function Sy() As String()
End Function
