VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ABC"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Public A$, B$, C$
'Property Get Init(Lin) As ABC
'Vb.Lin(Lin).AsgTTRst A, B, C
'Set Init = Me
'End Property
'Property Get ToStr$()
'ToStr = FmtQQ("A(?) B(?) C(?)", A, B, C)
'End Property
