VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CmdBrw"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Sub LoFmtrTp()
'Dim O$()
'Push O, "Lo  Nm     *Nm"
'Push O, "Lo  Fld    *Fld.."
'Push O, "Lo  Hid    *Fld.."
'Push O, "Bdr Left   *Fld.."
'Push O, "Bdr Right  *Fld.."
'Push O, "Bdr Col    *Fld.."
'Push O, "Tot Tot    *Fld.."
'Push O, "Tot Avg    *Fld.."
'Push O, "Tot Cnt    *Fld.."
'
'Push O, "Fmt *Fmt   *Fld.."
'Push O, "Wdt *Wdt   *Fld.."
'Push O, "Lvl *Lvl   *Fld.."
'Push O, "Cor *Cor   *Fld.."
'
'Push O, "Tit *Fld   *Tit"
'Push O, "Lbl *Fld   *Lbl"
'Push O, "Fml *Fld   *Formula"
'Push O, "Bet *Fld   *Fld1 *Fld2"
'AyBrw O
'End Sub
