VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Fml"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Private A$
'Const M_FmlEr$ = ""
'Friend Property Get Init(Fml$) As Fml
'A = Fml
'Set Init = Me
'End Property
'
'Function ErMsgOpt(Fny$()) As SomStr
'Dim N$(): N = Ny
'Dim F As Ay: Set F = Ay(Fny)
'Dim O$(), J%
'For J = 0 To UB(N)
'    If Not F.Has(N(J)) Then
'        Push O, N(J)
'    End If
'Next
'If AyIsEmp(O) Then Exit Function
'Dim M$:
'    Stop
'    'M = FmtQQ(M_FmlEr, A, Join(O, " "))
'ErMsgOpt = Vb.SomStr(M)
'End Function
'
'Property Get Ny() As String()
'Stop
''Ny = Macro(A).Ny(ExclBkt:=True, Bkt:="[]")
'End Property
'
