VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FmTos"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Private A() As FmTo
'Friend Property Get Init(Ay() As FmTo) As FmTos
'A = Ay
'Set Init = Me
'End Property
'Function LnoCnts() As LnoCnts
'If IsEmp Then Exit Function
'Dim U&, J&
'    U = FmTo_UB(A)
'Dim O() As LnoCnt
'   ReDim O(U)
'For J = 0 To U
'   O(J) = FmTo_LnoCnt(A(J))
'Next
'FmToAy_LnoCntAy = O
'End Function
'Property Get N&()
'N = U - 1
'End Property
'Property Get U&()
'U = UB(A)
'End Property
'Property Get IsEmp() As Boolean
'IsEmp = N = 0
'End Property
'
