VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FmTo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Public FmIx&, ToIx&
'Property Get Init(FmIx&, ToIx&) As FmTo
'Me.FmIx = FmIx
'Me.ToIx = ToIx
'Set Init = Me
'End Property
'
'Property Get Cnt&()
'Cnt = ToIx - FmIx + 1
'End Property
'
'Property Get ToStr$()
'ToStr = FmtQQ("FmTo(? ?)", FmIx, ToIx)
'End Property
'
'Function HasU(U&) As Boolean
'If U < 0 Then Stop
'If IsEmp Then Exit Function
'If FmIx > U Then Exit Function
'If ToIx < U Then Exit Function
'HasU = True
'End Function
'
'Function IsEmp() As Boolean
'IsEmp = True
'If FmIx < 0 Then Exit Function
'If ToIx < 0 Then Exit Function
'If FmIx > ToIx Then Exit Function
'IsEmp = False
'End Function
