VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Fxa"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Private A$
'
'Function Crt() As Excel.Application
'If IsExist Then MsgBox FmtQQ("Fxa.Crt: Fxa(?) exist", A): Exit Function
'Dim Wb As Workbook, X As Excel.Application
'   Set X = New Excel.Application
'   Set Wb = X.Workbooks.Add
'X.VBE.VBProjects(1).Name = FfnFnn(A)
'Wb.SaveAs A, XlFileFormat.xlOpenXMLAddIn
'Wb.Close
'X.AddIns.Add A
'Set Crt = X
'End Function
'
'Property Get IsExist() As Boolean
'IsExist = FfnIsExist(A)
'End Property
'
'Friend Property Get Init(Fxa) As Fxa
'A = DftFfn(Fxa, ".xlam")
'Set Init = Me
'End Property
'
'Private Sub ZZ_Crt()
'Dim Act As Excel.Application
'A = TmpFxa
'Set Act = Crt
'Act.Visible = True
'Stop
'End Sub
'
'Friend Sub Tst()
'ZZ_Crt
'End Sub
