VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IntAyObj"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Private B_Ay%()
'Private Const T$ = "InAyObj"
'Friend Property Get Init(Ay%()) As IntAyObj
'B_Ay = Ay
'Set Init = Me
'End Property
'Property Get ToStr$()
'ToStr = Tag("IntAyObj", JnCrLf(B_Ay, WithIx:=True))
'End Property
'
