VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "LnxsRslt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Public Lnxs As Lnx1s
'Private B_ErLy$()
'Friend Property Get Init(Lnxs As LnxsRslt, ErLy$()) As LnxsRslt
'Set Me.Lnxs = Lnxs
'B_ErLy = ErLy
'Set Init = Me
'End Property
'Property Get ErLy() As String()
'ErLy = B_ErLy
'End Property
