VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Logger"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'Sub Log(Msg$, Optional FilNum%)
'Dim F%
'   F = FilNum
'   If FilNum = 0 Then F = FilNum
'Print #F, NowStr & " " & Msg
'If FilNum = 0 Then Close #F
'End Sub
'
'Sub Brw()
'FtBrw Me.Ft
'End Sub
'
'Property Get FilNum%()
'FilNum = FtOpnApp(Me.Ft)
'End Property
'
'Property Get Ft$()
'Ft = Pth & "Log.txt"
'End Property
'
'Property Get Pth$()
'Dim O$:
'O = WrkPth: PthEns O
'O = O & "Log\": PthEns O
'Pth = O
'End Property
'
