VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "LyRslt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Option Explicit
'Private B_Ly$()
'Public Er As New Er
'
'Property Get Ly()
'Ly = B_Ly
'End Property
'
'Property Let Ly(V)
'B_Ly = V
'End Property
'
'Property Get ToStr$()
'ToStr = FmtQQ("LyRslt(|Ly(|?|)|?", JnCrLf(B_Ly), Er.ToStr)
'End Property
