VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Mdx"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Private A As CodeModule
'
'Property Get Init(Md As CodeModule) As Mdx
'Set A = Md
'Set Init = Me
'End Property
'
'Property Get Nm$()
'Nm = A.Parent.Name
'End Property
'
'Property Get Md() As CodeModule
'Set Md = A
'End Property
'
'Function Search$(RegExpStr)
'Stop
'End Function
