VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "RRCC"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Public R1&, R2&, C1&, C2&
'Property Get ToStr$()
'ToStr = FmtQQ("(RRCC : ? ? ? ??)", R1, R2, C1, C2)
'End Property
'
'Sub Dmp()
'Debug.Print ToStr
'End Sub
'
'Property Get IsEmp() As Boolean
'IsEmp = True
'If R1 <= 0 Then Exit Property
'If R2 <= 0 Then Exit Property
'If R1 > R2 Then Exit Property
'If R1 = R2 Then
'    If C1 > C2 Then Exit Property
'End If
'IsEmp = False
'End Property
'
