VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SqTpRslt"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Option Explicit
'Public Stmts$, Tp$
'Private B_Er$()
'Property Let Er(V$())
'B_Er = V
'End Property
'Property Get Er() As String()
'Er = B_Er
'End Property
'Property Get ToStr$()
'ToStr = Tag_NyStr_ObjAp("SqTpRslt", "Stmts Tp Er", StrObj(Stmts), StrObj(Tp), SyObj(Er))
'End Property
